### ISSUE TITLE
Add-on not working on Vaadin 24.4.0.alpha15

### ISSUE THREAD

**Issue by paodb** [FlowingCode/GridExporterAddon#104]
Latest version 2.2.1, is not working with Vaadin 24.4.0.alpha15

Browser console shows error: 

![image](https://github.com/FlowingCode/GridExporterAddon/assets/30666649/3adbad67-658f-44de-ba70-54db8762f6c7)

**Comment by paodb** [comment]
I did more testing and it seems it all worked okay up until alpha5, the error started from alpha7 (there's no alpha6).

**Comment by javier-godoy** [comment]
Is that error in development mode, production mode or both? Can you try alpha5 with intermediate Flow versions (alpha10 to alpha13)? [Vaadin 24.4.0.alpha5](https://github.com/vaadin/platform/releases/tag/24.4.0.alpha5) is based on Flow 24.4.0.alpha9 while [Vaadin 24.4.0.alpha7](https://github.com/vaadin/platform/releases/tag/24.4.0.alpha7) is based in Flow 24.4.0.alpha13,

**Comment by paodb** [comment]
Only tried dev mode, will try the other suggestions.

**Comment by paodb** [comment]
I did the test, with Vaadin 24.4.0.alpha5 and flow version from 24.4.0.alpha10 to 13 (and even 14) and it did not break. Tested both dev and prod mode.

**Comment by sveinnetnordic** [comment]
Same error in 24.4.0.alpha21

**Comment by sveinnetnordic** [comment]
In file: `node_modules/@flowingcode/font-awesome-iron-iconset/far.js`

If I remove `import '@vaadin/icon/vaadin-icon.js';` on line 25 it works.

Hope this can help you to fix this!

**Comment by javier-godoy** [comment]
> In file: `node_modules/@flowingcode/font-awesome-iron-iconset/far.js`
> 
> If I remove `import '@vaadin/icon/vaadin-icon.js';` on line 25 it works.
> 
> Hope this can help you to fix this!

Thanks. I'll look into it.

**Comment by sveinnetnordic** [comment]
Found this as a workaround:
       <dependency>
            <groupId>com.flowingcode.addons</groupId>
            <artifactId>font-awesome-iron-iconset</artifactId>
            <version>5.1.0</version>
        </dependency>

**Comment by javier-godoy** [comment]
Good catch. I hadn't realized that version 2.x of this addon (which is compatible with Vaadin 24) depends on FA 4.x (which is compatible with Vaadin 23). https://github.com/FlowingCode/GridExporterAddon/blob/3105a54ba08d23afc7ce256a4b6d6c4c54686aa9/pom.xml#L152-L154

**Comment by sveinnetnordic** [comment]
I hope for a new release soon!

**Comment by paodb** [comment]
@sveinnetnordic please check new released version 2.3.2.
