### ISSUE TITLE
Exported pdf is 0 bytes

### ISSUE THREAD

**Issue by drewharvey** [FlowingCode/GridExporterAddon#136]
### Describe the bug

I am able to download the PDF file but it is 0 bytes and fails to open.  All other file types download/open correctly.

![files](https://github.com/user-attachments/assets/6b5b0ec4-e5d1-446e-bc37-ab6c933388da)

### Expected behavior

PDF should have content and open as expected.

### Minimal reproducible example

```
var grid = new Grid<String>();
grid.addColumn(String::toString).setHeader("Name");
grid.addColumn(String::toString).setHeader("Email");

grid.setItems("A", "B", "C");

var exporter = GridExporter.createFor(grid);
exporter.setTitle("Grid Export Title");
exporter.setFileName("GridExport_" + new SimpleDateFormat("yyyyddMM").format(Calendar.getInstance().getTime()));
exporter.setAutoAttachExportButtons(true);

add(grid);
```

### Add-on Version

2.3.2

### Vaadin Version

24.4.3

### Additional information

Chrome (latest)

**Comment by mlopezFC** [comment]
Hi @drewharvey ! ... thanks for the issue!
When one of the downloaded files is 0 bytes, that usually mean that a problem happened when generating the file. We have to fix this known issue (the exception logging is not correctly implemented), but can you add a breakpoint and debug [this method](https://github.com/FlowingCode/GridExporterAddon/blob/ec5d5ad7bda3d1509a95c3af7a2daac17b3c7521/src/main/java/com/flowingcode/vaadin/addons/gridexporter/PdfInputStreamFactory.java#L50) to see if the generation happens correctly or there is an exception being hidden?

**Comment by drewharvey** [comment]
Problem occurs here: https://github.com/FlowingCode/GridExporterAddon/blob/ec5d5ad7bda3d1509a95c3af7a2daac17b3c7521/src/main/java/com/flowingcode/vaadin/addons/gridexporter/PdfInputStreamFactory.java#L62

Here the stacktrace:
```
Exception in thread "Thread-83" java.lang.NoClassDefFoundError: javax/xml/bind/ValidationEventHandler
	at com.flowingcode.vaadin.addons.gridexporter.PdfInputStreamFactory$1.run(PdfInputStreamFactory.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationEventHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 2 more
```

**Comment by mlopezFC** [comment]
Maybe [this](https://github.com/FlowingCode/GridExporterAddon/issues/57#issuecomment-1648546676) can also work for this issue, can you give it a try?

**Comment by drewharvey** [comment]
@mlopezFC Adding the maven dependencies in your link did fix the issue.  

However, it is still doesn't work with a fresh project from [vaadin.start.com](http://vaadin.start.com).  For this project specificially, it seems to be caused by `spring-boot-starter-data-jpa`.

Has anyone looked into using docx4j 11.5.0?

**Comment by drewharvey** [comment]
I was able to update/add some deps to the GridExporterAddon project and was able to successfully export as pdf.

```java 
// remove docx4j-JAXB-Internal
<dependency>
   <groupId>org.docx4j</groupId>
   <artifactId>docx4j-JAXB-Internal</artifactId>
   <version>8.3.8</version>
</dependency>

// update other docx4j dep versions
<dependency>
	<groupId>org.docx4j</groupId>
	<artifactId>docx4j-JAXB-ReferenceImpl</artifactId>
	<version>11.5.0</version>
</dependency>
<dependency>
	<groupId>org.docx4j</groupId>
	<artifactId>docx4j-JAXB-MOXy</artifactId>
	<version>11.5.0</version>
</dependency>
<dependency>
	<groupId>org.docx4j</groupId>
	<artifactId>docx4j-export-fo</artifactId>
	<version>11.5.0</version>
</dependency>

// add following
<dependency>
	<groupId>org.apache.commons</groupId>
	<artifactId>commons-compress</artifactId>
	<version>1.27.1</version>
</dependency>
<dependency>
	<groupId>commons-io</groupId>
	<artifactId>commons-io</artifactId>
	<version>2.16.1</version>
</dependency>
```
