### ISSUE TITLE
Release notes for 1.1.0 are wrong

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/GridExporterAddon#17]
The [release notes](https://github.com/FlowingCode/GridExporterAddon/releases/tag/grid-exporter-addon-1.1.0) mention "Fix issues by @mlopezFC in https://github.com/FlowingCode/GridExporterAddon/pull/13", but that PR contains four *features*.

- [feat: add support for custom null value handler](https://github.com/FlowingCode/GridExporterAddon/pull/13/commits/308472df1beeae7a6ef0f9628117ef8f73f491c1) 
- [feat: add proper handling of missing optional placeholders](https://github.com/FlowingCode/GridExporterAddon/pull/13/commits/39dfedc3ea863fbe14f75f071a2be9205f36f751) 

- [feat: add support for BasicRenderers such as LocalDateRenderer](https://github.com/FlowingCode/GridExporterAddon/pull/13/commits/6911602685e6deed79b091114252535fcd52a64b) 
- [feat: add support for auto width in excel columns](https://github.com/FlowingCode/GridExporterAddon/pull/13/commits/6fe54e9774cbedf559592769b858359065053f27)

**Comment by mlopezFC** [comment]
Thanks for noting. I updated the release notes.
