### ISSUE TITLE
Add support for setting the alignment that apply to individual cells

### ISSUE THREAD

**Issue by mlopezFC** [FlowingCode/GridExporterAddon#25]
It is a usual requirement that numbers should be right aligned and text left aligned, so it should be possible to customize that for excel, docx and pdf outputs.

**Comment by javier-godoy** [comment]
Isn't enough with taking `Grid.getTextAlignment` into account when generating the output? (the value is already set, not for individual cells but for the column as a whole, which suffices for the proposed use case)

**Comment by mlopezFC** [comment]
Good catch! .. I like the idea so the API is easier. Let's use that approach.
