### ISSUE TITLE
CSV export of a grid without a footer adds an empty row at the bottom of the exported file.

### ISSUE THREAD

**Issue by anne-k** [FlowingCode/GridExporterAddon#46]
Title basically, I don't know the exact circumstances but I seem to be getting it consistently on grids that don't have a footer row.

Vaadin version 23.3.2, addon version 1.4.0

**Comment by paodb** [comment]
I was able to reproduce the issue enabling cvs export on [this demo example](https://github.com/FlowingCode/GridExporterAddon/blob/master/src/test/java/com/flowingcode/vaadin/addons/gridexporter/GridExporterCustomTemplateDemo.java).

Cvs exported file shows an "empty" row at the end:
![image](https://user-images.githubusercontent.com/30666649/214323827-46868780-9217-4799-b2e4-182837d3d88d.png)


It seems we're missing checking if the grid has no footer [here](https://github.com/FlowingCode/GridExporterAddon/blob/1bf06bc42e2992919641aa77e7add1c89314e16a/src/main/java/com/flowingcode/vaadin/addons/gridexporter/CsvInputStreamFactory.java#L53).
