### ISSUE TITLE
Exporting columns that are defined by ComponentRenderer

### ISSUE THREAD

**Issue by josegulisano** [FlowingCode/GridExporterAddon#79]
I have several grid columns that have custom renderers
`Column myColumn = this.addColumn(new ComponentRenderer<>(this::createUserNumber))`

These columns do not get included in the export.  Is there a way to configure the exporter to include these values as part of the export?

**Comment by mlopezFC** [comment]
You can create a hidden column (`column.setVisible(false)`) that will render the values that you would like to see in the export, and configure them to be included in the report with `exporter.setExportColumn(hiddenColumn, true);`
There is an example of this [in the demo](https://addonsv24.flowingcode.com/gridexporter/custom-columns) (see lastName column)

**Comment by josegulisano** [comment]
I missed that detail when going through the demos.  Thanks for the quick response.
