### ISSUE TITLE
extractValueFromColumn throws Exception when no value can be obtained

### ISSUE THREAD

**Issue by TorstenBMR** [FlowingCode/GridExporterAddon#9]
Can you please just offer the possibility to return a null value in that case?
That would give the possibility to use your exporter for all grids without the risk that someone somewhere adds a non-exportable column and the user will get an exception.
You could probably add a "general null value handler" that generates the default-value for null-columns (if no custom _column-value-provider-data_ is set).

```
if (value == null) {
      throw new IllegalStateException("It's not possible to obtain a value for column, please set a value provider by calling setExportValue()");
}

```

**Comment by mlopezFC** [comment]
Hi. I implemented the fix, but I don't know how to reproduce the issue.
Suppose there is a null in the field "lastName" of Person object, and I have it defined as this:
```
grid.addColumn("lastName").setHeader("Last Name");
```
The grid itself will render it as an empty string, not null, so it won't throw the exception.
Is there a particular setup for the grid that caused the issue to you? can you supply a snippet of code?
Thanks!
